# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: False

# Setup
title:            HeeHyeon
tagline:          'Home'
description:     Image Processing With Deep Learning
url:              https://heehyeonkim.github.io/
baseurl:          

author:
  name:           'HeeHyeon Kim'
  url:            ""

paginate:         5


github:           
  repo:           https://github.com/HeeHyeonKim
